
import sys
import os
import time
import logging

# Add project root to path
sys.path.append(os.getcwd())

from src.db.oracle import get_oracle_connection
from src.config import Config
import oracledb

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_test_data():
    """Create a test table and insert data in Oracle."""
    max_retries = 30
    retry_delay = 5
    
    logger.info(f"Attempting to connect to Oracle at {Config.ORACLE_HOST}:{Config.ORACLE_PORT}...")
    
    for i in range(max_retries):
        try:
            conn = get_oracle_connection()
            cursor = conn.cursor()
            
            # Create table
            try:
                cursor.execute("DROP TABLE test_users PURGE")
            except Exception:
                pass
                
            logger.info("Creating table TEST_USERS...")
            cursor.execute("""
                CREATE TABLE test_users (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(50) NOT NULL,
                    email VARCHAR2(100),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    score NUMBER(5,2)
                )
            """)
            
            # Insert data
            logger.info("Inserting test data...")
            data = [
                ('alice', 'alice@example.com', 95.5),
                ('bob', 'bob@example.com', 80.0),
                ('charlie', None, 60.5)
            ]
            
            cursor.executemany(
                "INSERT INTO test_users (username, email, score) VALUES (:1, :2, :3)",
                data
            )
            
            conn.commit()
            logger.info("Test data created successfully.")
            
            cursor.close()
            conn.close()
            return True
            
        except Exception as e:
            logger.warning(f"Connection attempt {i+1}/{max_retries} failed: {e}")
            if i < max_retries - 1:
                time.sleep(retry_delay)
                
    logger.error("Failed to connect to Oracle as configured user.")
    
    # Try connecting as SYSTEM to debug
    logger.info("Tentatively trying to connect as SYSTEM...")
    try:
        params = oracledb.ConnectParams(
            host=Config.ORACLE_HOST,
            port=Config.ORACLE_PORT,
            service_name=Config.ORACLE_SERVICE_NAME
        )
        conn = oracledb.connect(
            user="SYSTEM",
            password=Config.ORACLE_PASSWORD,
            params=params
        )
        logger.info("SUCCESS: Connected as SYSTEM!")
        
        # Check if user exists
        cursor = conn.cursor()
        cursor.execute("SELECT username FROM all_users WHERE username = :1", (Config.ORACLE_USER.upper(),))
        row = cursor.fetchone()
        if row:
            logger.info(f"User {Config.ORACLE_USER} exists.")
        else:
            logger.warning(f"User {Config.ORACLE_USER} DOES NOT EXIST.")
            
        cursor.close()
        conn.close()
    except Exception as e:
        logger.error(f"Failed to connect as SYSTEM: {e}")

    return False

if __name__ == '__main__':
    if create_test_data():
        sys.exit(0)
    else:
        sys.exit(1)
