
-- Fix PROD user permissions
-- Run as SYSTEM

BEGIN
   EXECUTE IMMEDIATE 'DROP USER PROD CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      NULL; -- Ignore if user doesn't exist
END;
/

CREATE USER PROD IDENTIFIED BY "password123";
GRANT CONNECT, RESOURCE TO PROD;
GRANT UNLIMITED TABLESPACE TO PROD;
GRANT CREATE SESSION TO PROD;
GRANT CREATE TABLE TO PROD;
GRANT CREATE VIEW TO PROD;
GRANT CREATE PROCEDURE TO PROD;
GRANT CREATE TRIGGER TO PROD;

EXIT;
