-- Sample data for testing DataProfiler (Oracle 21c XE)
-- Compatible with 19c/21c (No IF NOT EXISTS, No BOOLEAN)

-- ==========================================
-- 1. Production Environment (Golden Schema)
-- ==========================================

-- Switch to PROD schema context for following commands
ALTER SESSION SET CURRENT_SCHEMA = PROD;

-- Users Table
DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'PROD' AND table_name = 'USERS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE users (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL,
                email VARCHAR2(100) NOT NULL,
                age Number,
                salary Number(10, 2),
                is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ';
    END IF;
END;
/

-- Users Indexes
DECLARE
    idx_exists INT;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'PROD' AND index_name = 'IDX_USERS_USERNAME';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_users_username ON users(username)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'PROD' AND index_name = 'IDX_USERS_AGE_SALARY';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_users_age_salary ON users(age, salary)';
    END IF;

    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'PROD' AND index_name = 'IDX_USERS_EMAIL';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX idx_users_email ON users(email)';
    END IF;
END;
/

-- Products Table
DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'PROD' AND table_name = 'PRODUCTS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE products (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                category VARCHAR2(50),
                price Number(10, 2),
                stock_quantity Number,
                is_available NUMBER(1) DEFAULT 1 CHECK (is_available IN (0, 1))
            )
        ';
    END IF;
END;
/

-- Products Indexes
DECLARE
    idx_exists INT;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'PROD' AND index_name = 'IDX_PRODUCTS_CATEGORY';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_products_category ON products(category)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'PROD' AND index_name = 'IDX_PRODUCTS_PRICE';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_products_price ON products(price)';
    END IF;
END;
/


-- Insert sample data into PROD (using 1/0 for boolean)
BEGIN
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('john_doe', 'john@company.com', 35, 75000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('jane_smith', 'jane@company.com', 42, 92000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('bob_wilson', 'bob@company.com', 51, 105000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('alice_johnson', 'alice@company.com', 38, 82000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('charlie_brown', 'charlie@company.com', 45, 98000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('diana_prince', 'diana@company.com', 39, NULL, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('edward_stark', 'edward@company.com', 55, 130000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('fiona_green', 'fiona@company.com', 33, 68000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('george_lucas', 'george@company.com', 48, 115000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('hannah_montana', 'hannah@company.com', 29, 58000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('ivan_petrov', 'ivan@company.com', 44, 88000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('julia_roberts', 'julia@company.com', 41, 95000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('kevin_hart', 'kevin@company.com', 36, 72000.00, 0);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('laura_palmer', 'laura@company.com', 32, 64000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('mike_tyson', 'mike@company.com', 50, 108000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('nancy_drew', 'nancy@company.com', 28, 55000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('oscar_wilde', 'oscar@company.com', 46, 99000.00, 0);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('paula_abdul', 'paula@company.com', 43, 86000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('quentin_beck', 'quentin@company.com', 37, 76000.00, 1);
    INSERT INTO users (username, email, age, salary, is_active) VALUES ('rachel_green', 'rachel@company.com', 34, 70000.00, 1);

    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Laptop Pro 16', 'Electronics', 1499.99, 50, 1);
    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Laptop Air 13', 'Electronics', 999.99, 75, 1);
    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Wireless Mouse Pro', 'Electronics', 49.99, 200, 1);
    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Office Chair Standard', 'Furniture', 249.99, 30, 1);
    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Coffee Maker Drip', 'Appliances', 89.99, 60, 1);
    INSERT INTO products (name, category, price, stock_quantity, is_available) VALUES ('Notebook Set Premium', 'Stationery', 18.99, 500, 1);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore dupes
END;
/


-- ==========================================
-- 2. UAT Environment (Simulated Drift)
-- ==========================================

-- Switch to UAT schema
ALTER SESSION SET CURRENT_SCHEMA = UAT;

DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'UAT' AND table_name = 'USERS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE users (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL,
                -- Drift: different length
                email VARCHAR2(150),
                -- Drift: NOT NULL in UAT (vs nullable via pattern in Prod)
                age Number,
                -- Drift: different precision
                salary Number(12, 2),
                is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                -- Drift: Extra column in UAT
                middle_name VARCHAR2(50)
            )
        ';
    END IF;
END;
/


-- UAT Indexes 
DECLARE
    idx_exists INT;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'UAT' AND index_name = 'IDX_USERS_AGE_SALARY_UAT';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_users_age_salary_uat ON users(age, salary)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'UAT' AND index_name = 'IDX_USERS_EMAIL_UAT';
    IF idx_exists = 0 THEN
        -- Drift: Using a different name just to be safe with global names if any
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX idx_users_email_uat ON users(email)';
    END IF;
END;
/


-- Insert sample data into UAT
BEGIN
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('john_doe', 'john@testmail.io', 35, 72000.00, 1, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('jane_smith', 'jane@testmail.io', 42, 89000.00, 1, 'Marie');
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('bob_wilson', 'bob@testmail.io', 51, 102000.00, 1, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('alice_johnson', 'alice@testmail.io', 38, 79000.00, 0, 'Grace');
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('charlie_brown', 'charlie@testmail.io', NULL, 95000.00, 1, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('diana_prince', 'diana@testmail.io', 39, NULL, 1, 'Athena');
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('edward_stark', 'edward@testmail.io', 55, 128000.00, 1, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('fiona_green', 'fiona@testmail.io', 33, 65000.00, 0, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('george_lucas', 'george@testmail.io', 48, 112000.00, 1, 'Walton');
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('hannah_montana', 'hannah@testmail.io', 29, 55000.00, 1, NULL);
    INSERT INTO users (username, email, age, salary, is_active, middle_name) VALUES ('kevin_hart', 'kevin@testmail.io', 36, 70000.00, 1, 'Darnell');
    
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN NULL;
END;
/


-- UAT Products
DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'UAT' AND table_name = 'PRODUCTS';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE products (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                -- Drift: VARCHAR(80)
                category VARCHAR2(80),
                -- Drift: Number(12,4)
                price Number(12, 4),
                stock_quantity Number,
                is_available NUMBER(1) DEFAULT 1 CHECK (is_available IN (0, 1)),
                -- Drift: Extra columns
                sku VARCHAR2(30),
                discount_percent Number(5,2)
            )
        ';
    END IF;
END;
/

-- UAT Products Indexes
DECLARE
    idx_exists INT;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM all_indexes WHERE owner = 'UAT' AND index_name = 'IDX_PRODUCTS_CATEGORY_UAT';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_products_category_uat ON products(category)';
    END IF;
END;
/

-- Insert sample data
BEGIN
    INSERT INTO products (name, category, price, stock_quantity, is_available, sku, discount_percent) VALUES ('Laptop Pro 16', 'Electronics', 1399.9900, 30, 1, 'ELEC-LP16-001', 5.00);
    INSERT INTO products (name, category, price, stock_quantity, is_available, sku, discount_percent) VALUES ('Laptop Air 13', 'Electronics', 949.9900, 45, 1, 'ELEC-LA13-002', 8.00);
    INSERT INTO products (name, category, price, stock_quantity, is_available, sku, discount_percent) VALUES ('Wireless Mouse Pro', 'Electronics', 44.9900, 150, 1, 'ELEC-WMP-003', NULL);

    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN NULL;
END;
/
