-- Schema Objects for testing DataProfiler (Oracle 21c XE)
-- Compatible with 19c/21c (No IF NOT EXISTS, No BOOLEAN)

-- ==========================================
-- 1. PROD Schema Objects (Golden Standard)
-- ==========================================

ALTER SESSION SET CURRENT_SCHEMA = PROD;

-- ----- Stored Procedures -----

-- Procedure: get user by ID
CREATE OR REPLACE PROCEDURE get_user_by_id(p_user_id IN Number)
AS
    v_username users.username%TYPE;
    v_email users.email%TYPE;
    v_salary users.salary%TYPE;
BEGIN
    SELECT username, email, salary
    INTO v_username, v_email, v_salary
    FROM users
    WHERE id = p_user_id;

    DBMS_OUTPUT.PUT_LINE('User: ' || v_username || ', Email: ' || v_email);
END;
/

-- Procedure: deactivate user (using 0 for FALSE)
CREATE OR REPLACE PROCEDURE deactivate_user(p_user_id IN Number)
AS
BEGIN
    UPDATE users SET is_active = 0 WHERE id = p_user_id;
END;
/

-- ----- Views -----

-- View: active users summary (is_active = 1)
CREATE OR REPLACE VIEW v_active_users AS
SELECT id, username, email, age, salary, created_at
FROM users
WHERE is_active = 1;

-- View: product inventory (is_available = 1)
CREATE OR REPLACE VIEW v_product_inventory AS
SELECT id, name, category, price, stock_quantity,
       CASE WHEN stock_quantity > 0 AND is_available = 1 THEN 'In Stock'
            WHEN stock_quantity = 0 THEN 'Out of Stock'
            ELSE 'Unavailable' END AS availability_status
FROM products;

-- View: category summary
CREATE OR REPLACE VIEW v_category_summary AS
SELECT category,
       COUNT(*) AS product_count,
       ROUND(AVG(price), 2) AS avg_price,
       SUM(stock_quantity) AS total_stock,
       SUM(CASE WHEN is_available = 1 THEN 1 ELSE 0 END) AS available_count
FROM products
GROUP BY category;


-- ----- Triggers -----

-- Audit log table (use PL/SQL to check existence)
DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'PROD' AND table_name = 'USER_AUDIT_LOG';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE user_audit_log (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id Number,
                action VARCHAR2(10),
                old_email VARCHAR2(100),
                new_email VARCHAR2(100),
                changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ';
    END IF;
END;
/

-- Trigger: log user email changes
CREATE OR REPLACE TRIGGER trg_user_audit
    AFTER UPDATE ON users
    FOR EACH ROW
BEGIN
    IF :OLD.email <> :NEW.email THEN
        INSERT INTO user_audit_log (user_id, action, old_email, new_email)
        VALUES (:NEW.id, 'UPDATE', :OLD.email, :NEW.email);
    END IF;
END;
/

-- Trigger: validate product price before insert
CREATE OR REPLACE TRIGGER trg_validate_price_insert
    BEFORE INSERT ON products
    FOR EACH ROW
BEGIN
    IF :NEW.price < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Product price cannot be negative');
    END IF;
END;
/

-- Trigger: validate product price before update
CREATE OR REPLACE TRIGGER trg_validate_price_update
    BEFORE UPDATE ON products
    FOR EACH ROW
BEGIN
    IF :NEW.price < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Product price cannot be negative');
    END IF;
END;
/


-- ==========================================
-- 2. UAT Schema Objects (Simulated Drift)
-- ==========================================

ALTER SESSION SET CURRENT_SCHEMA = UAT;

-- ----- Stored Procedures -----

-- SAME as prod
CREATE OR REPLACE PROCEDURE get_user_by_id(p_user_id IN Number)
AS
    v_username users.username%TYPE;
    v_email users.email%TYPE;
    v_salary users.salary%TYPE;
BEGIN
    SELECT username, email, salary
    INTO v_username, v_email, v_salary
    FROM users
    WHERE id = p_user_id;
END;
/

-- SAME as prod
CREATE OR REPLACE PROCEDURE deactivate_user(p_user_id IN Number)
AS
BEGIN
    UPDATE users SET is_active = 0 WHERE id = p_user_id;
END;
/

-- DRIFT: extra procedure not in prod
CREATE OR REPLACE PROCEDURE bulk_deactivate_test_users
AS
BEGIN
    UPDATE users SET is_active = 0
    WHERE username LIKE 'load_test%' OR username LIKE 'temp_%';
END;
/


-- ----- Views -----

-- DRIFT: includes middle_name
CREATE OR REPLACE VIEW v_active_users AS
SELECT id, username, email, age, salary, middle_name, created_at
FROM users
WHERE is_active = 1;

-- DRIFT: includes sku and discount_percent
CREATE OR REPLACE VIEW v_product_inventory AS
SELECT id, name, category, price, stock_quantity, sku, discount_percent,
       CASE WHEN stock_quantity > 0 AND is_available = 1 THEN 'In Stock'
            WHEN stock_quantity = 0 OR stock_quantity IS NULL THEN 'Out of Stock'
            ELSE 'Unavailable' END AS availability_status
FROM products;

-- DRIFT: includes avg_discount
CREATE OR REPLACE VIEW v_category_summary AS
SELECT category,
       COUNT(*) AS product_count,
       ROUND(AVG(price), 2) AS avg_price,
       SUM(stock_quantity) AS total_stock,
       SUM(CASE WHEN is_available = 1 THEN 1 ELSE 0 END) AS available_count,
       ROUND(AVG(COALESCE(discount_percent, 0)), 2) AS avg_discount
FROM products
GROUP BY category;

-- DRIFT: extra view not in prod
CREATE OR REPLACE VIEW v_test_users AS
SELECT id, username, email, middle_name
FROM users
WHERE username LIKE 'new_hire%'
   OR username LIKE 'intern_%'
   OR username LIKE 'load_test%'
   OR username LIKE 'temp_%';


-- ----- Triggers -----

-- Audit log table (same structure + extra column)
DECLARE
    table_exists INT;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM all_tables WHERE owner = 'UAT' AND table_name = 'USER_AUDIT_LOG';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE user_audit_log (
                id Number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id Number,
                action VARCHAR2(10),
                old_email VARCHAR2(150),
                new_email VARCHAR2(150),
                changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                changed_by VARCHAR2(50) DEFAULT USER
            )
        ';
    END IF;
END;
/


-- DRIFT: trigger logs extra info (changed_by)
CREATE OR REPLACE TRIGGER trg_user_audit
    AFTER UPDATE ON users
    FOR EACH ROW
BEGIN
    IF :OLD.email <> :NEW.email THEN
        INSERT INTO user_audit_log (user_id, action, old_email, new_email, changed_by)
        VALUES (:NEW.id, 'UPDATE', :OLD.email, :NEW.email, USER);
    END IF;
END;
/

-- DRIFT: extra trigger not in prod — auto-set created_at
CREATE OR REPLACE TRIGGER trg_set_created_at
    BEFORE INSERT ON users
    FOR EACH ROW
BEGIN
    :NEW.created_at := CURRENT_TIMESTAMP;
END;
/
